### ISSUE TITLE
'module' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by ghost** [tqvinhcs/C3D-tensorflow#1]
I cloned the repository and tried to run m_c3d.py. I got the following error.

File "m_c3d.py", line 357, in <module>
    demo_test()
  File "m_c3d.py", line 245, in demo_test
    logits = c3d_ucf101(inputs=inputs, training=training, weights=weights)
  File "m_c3d.py", line 109, in c3d_ucf101
    net = tf.layers.flatten(net)
AttributeError: 'module' object has no attribute 'flatten'

But my tensorflow version is 1.3.0.
Not sure the reason of the error. Appreciated for any suggestions.

**Comment by tqvinhcs** [comment]
tf.layers.flatten is in version 1.4. For older version, net = tf.contrib.layers.flatten(net) should work.

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
I am able to compile now. Awesome repository.
