### ISSUE TITLE
How to prepare my own dataset?

### ISSUE THREAD

**Issue by lucasjinreal** [tqvinhcs/C3D-tensorflow#3]
Hi, is there any instructions or preparations of the input dataset?

**Comment by tqvinhcs** [comment]
Hi, 
in m_c3d.py there are some demo code for finetune the network. Line 298, def demo_finetune():

**Comment by Villjoie** [comment]
I didn't find m_c3d.py

**Comment by tqvinhcs** [comment]
https://github.com/tqvinhcs/C3D-tensorflow/blob/master/m_c3d.py

**Comment by Villjoie** [comment]
@tqvinhcs, Thank you
