### ISSUE TITLE
I don't understand that line

### ISSUE THREAD

**Issue by mourad1081** [tqvinhcs/C3D-tensorflow#4]
https://github.com/tqvinhcs/C3D-tensorflow/blob/6267a141c004ee9929f2abb79875d1b27939516a/m_c3d.py#L312

Why 96.6? What is the purpose of that number please?

**Comment by tqvinhcs** [comment]
This is for mean subtraction for each R,G,B channels. Here, I used the same value 96.9 for all. 
For old style CNNs, people usually did that.

**Comment by mourad1081** [comment]
> This is for mean subtraction for each R,G,B channels. Here, I used the same value 96.9 for all.
> For old style CNNs, people usually did that.

Thank you for your reply. But what I do not understand is why 96.9 for all videos? From what I understand about mean substraction, we have to substracte the current pixel by the mean value of all pixels at the same coordinate in the video. (I am quite new in the AI field, sorry if I say something wrong.)

**Comment by tqvinhcs** [comment]
No need for that. If you look at the code of training image net, they subtract the same mean of R,G,B at every location. Here, I used the same value 96.9 for R,G,B since I was lazy :p.

**Comment by mourad1081** [comment]
Thank you :) !
