### ISSUE TITLE
code for generating train.txt and test.txt?

### ISSUE THREAD

**Issue by ramnamaqsood776** [tqvinhcs/C3D-tensorflow#6]
Hello
I just want to know that which code you have used for generating c3d_train.txt and c3d_val.txt?
could you please share that code?
Thanks

**Comment by nimit1997** [comment]
Any update with the training and testing codes?

**Comment by tqvinhcs** [comment]
I did not keep the code to generate these files.
However, it is easy to use glob to count the number of frames in each dir.

**Comment by ramnamaqsood776** [comment]
Thank you for your reply
I have a query regarding weights. I am using your code for my own dataset but you didn't specify in your code that how to save trained weights file after training.?

**Comment by tqvinhcs** [comment]
You can add these lines to save your model
# Add ops to save and restore all the variables.
saver = tf.train.Saver()
...
save_path = saver.save(sess, "/tmp/model_c3d.ckpt")

An example of saving a model in tensorflow can be found here:
https://www.tensorflow.org/guide/saved_model

**Comment by nimit1997** [comment]
How to restore the saved model for testing ?
